In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv("AMESFINAL.csv")

In [5]:
df.head()

,Unnamed: 0,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [10]:
df=df.drop(['Order'],axis=1)

In [11]:
df.head()

,Unnamed: 0,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,0,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,1,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,2,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,3,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,4,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [13]:
df=df.drop(['Unnamed: 0'],axis=1)

In [14]:
df.head()

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2927 entries, 0 to 2926
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PID              2927 non-null   int64
 1   MS SubClass      2927 non-null   int64
 2   MS Zoning        2927 non-null   object
 3   Lot Frontage     2437 non-null   float64
 4   Lot Area         2927 non-null   int64
 5   Street           2927 non-null   object
 6   Alley            198 non-null    object
 7   Lot Shape        2927 non-null   object
 8   Land Contour     2927 non-null   object
 9   Utilities        2927 non-null   object
 10  Lot Config       2927 non-null   object
 11  Land Slope       2927 non-null   object
 12  Neighborhood     2927 non-null   object
 13  Condition 1      2927 non-null   object
 14  Condition 2      2927 non-null   object
 15  Bldg Type        2927 non-null   object
 16  House Style      2927 non-null   object
 17  Overall Qual     2927 non-null   int64
 18  Overall Cond     2927 non-null   int64
 19  Year Built       2927 non-null   int64
 20  Year Remod/Add   2927 non-null   int64
 21  Roof Style       2927 non-null   object
 22  Roof Matl        2927 non-null   object
 23  Exterior 1st     2927 non-null   object
 24  Exterior 2nd     2927 non-null   object
 25  Mas Vnr Type     1152 non-null   object
 26  Mas Vnr Area     2904 non-null   float64
 27  Exter Qual       2927 non-null   object
 28  Exter Cond       2927 non-null   object
 29  Foundation       2927 non-null   object
 30  Bsmt Qual        2847 non-null   object
 31  Bsmt Cond        2847 non-null   object
 32  Bsmt Exposure    2844 non-null   object
 33  BsmtFin Type 1   2847 non-null   object
 34  BsmtFin SF 1     2926 non-null   float64
 35  BsmtFin Type 2   2846 non-null   object
 36  BsmtFin SF 2     2926 non-null   float64
 37  Bsmt Unf SF      2926 non-null   float64
 38  Total Bsmt SF    2926 non-null   float64
 39  Heating          2927 non-null   object
 40  Heating QC       2927 non-null   object
 41  Central Air      2927 non-null   object
 42  Electrical       2926 non-null   object
 43  1st Flr SF       2927 non-null   int64
 44  2nd Flr SF       2927 non-null   int64
 45  Low Qual Fin SF  2927 non-null   int64
 46  Gr Liv Area      2927 non-null   int64
 47  Bsmt Full Bath   2925 non-null   float64
 48  Bsmt Half Bath   2925 non-null   float64
 49  Full Bath        2927 non-null   int64
 50  Half Bath        2927 non-null   int64
 51  Bedroom AbvGr    2927 non-null   int64
 52  Kitchen AbvGr    2927 non-null   int64
 53  Kitchen Qual     2927 non-null   object
 54  TotRms AbvGrd    2927 non-null   int64
 55  Functional       2927 non-null   object
 56  Fireplaces       2927 non-null   int64
 57  Fireplace Qu     1505 non-null   object
 58  Garage Type      2770 non-null   object
 59  Garage Yr Blt    2768 non-null   float64
 60  Garage Finish    2768 non-null   object
 61  Garage Cars      2926 non-null   float64
 62  Garage Area      2926 non-null   float64
 63  Garage Qual      2768 non-null   object
 64  Garage Cond      2768 non-null   object
 65  Paved Drive      2927 non-null   object
 66  Wood Deck SF     2927 non-null   int64
 67  Open Porch SF    2927 non-null   int64
 68  Enclosed Porch   2927 non-null   int64
 69  3Ssn Porch       2927 non-null   int64
 70  Screen Porch     2927 non-null   int64
 71  Pool Area        2927 non-null   int64
 72  Pool QC          12 non-null     object
 73  Fence            572 non-null    object
 74  Misc Feature     105 non-null    object
 75  Misc Val         2927 non-null   int64
 76  Mo Sold          2927 non-null   int64
 77  Yr Sold          2927 non-null   int64
 78  Sale Type        2927 non-null   object
 79  Sale Condition   2927 non-null   object
 80  SalePrice        2927 non-null   int64
dtypes: float64(11), int64(27), object(43)
memory usage: 1.8+ MB

In [16]:
X=df.drop('SalePrice',axis=1)

In [17]:
y=df['SalePrice']

In [18]:
from sklearn.model_selection import train_test_split
X_train,y_train,X_test,y_test=train_test_split(X,y,test_size=0.1,random_state=101)

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
scaler=StandardScaler()

In [21]:
scaled_X_train=scaler.fit_transform(X_train)

ValueError: could not convert string to float: 'RL'

In [22]:
print(X_train.dtypes)

PID                 int64
MS SubClass         int64
MS Zoning          object
Lot Frontage      float64
Lot Area            int64
                   ...
Misc Val            int64
Mo Sold             int64
Yr Sold             int64
Sale Type          object
Sale Condition     object
Length: 80, dtype: object

In [23]:
X = pd.get_dummies(X, drop_first=True)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [25]:
from sklearn.linear_model import ElasticNet

In [ ]:
base_elastic_model=ElasticNet(max_ters=1000000)

In [27]:
param_grid={'alpha':[0.1,1,5,10,100],'l1_ratio':[.1,.7,.99,1]}

In [28]:
from sklearn.model_selection import GridSearchCV

In [29]:
grid_model=GridSearchCV(base_elastic_model,
param_grid=param_grid,
scoring='neg_mean_squared_error',
cv=5,
verbose=1)

In [31]:
X_train.isna().sum()

PID                         0
MS SubClass                 0
Lot Frontage              348
Lot Area                    0
Overall Qual                0
                         ...
Sale Condition_AdjLand      0
Sale Condition_Alloca       0
Sale Condition_Family       0
Sale Condition_Normal       0
Sale Condition_Partial      0
Length: 259, dtype: int64

In [32]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

In [34]:
grid_model.fit(scaled_X_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

ValueError:
All the 100 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
100 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Kirat\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kirat\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\Kirat\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py", line 986, in fit
    X, y = validate_data(
           ~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<9 lines>...
        y_numeric=True,
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Kirat\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py", line 2971, in validate_data
    X, y = check_X_y(X, y, **check_params)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kirat\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py", line 1368, in check_X_y
    X = check_array(
        X,
    ...<12 lines>...
        input_name="X",
    )
  File "C:\Users\Kirat\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py", line 1105, in check_array
    _assert_all_finite(
    ~~~~~~~~~~~~~~~~~~^
        array,
        ^^^^^^
    ...<2 lines>...
        allow_nan=ensure_all_finite == "allow-nan",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Kirat\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py", line 120, in _assert_all_finite
    _assert_all_finite_element_wise(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        X,
        ^^
    ...<4 lines>...
        input_name=input_name,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Kirat\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py", line 169, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
ElasticNet does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [35]:
grid_model.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [36]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import ElasticNet

pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler()),
    ('model', ElasticNet())
])

pipe.fit(X_train, y_train)

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('model', ElasticNet())])

In [38]:
pipe.best_params_

AttributeError: 'Pipeline' object has no attribute 'best_params_'